### ISSUE TITLE
[minor] simplify node installation in e2e-contract.yml

### ISSUE THREAD

**Issue by meleu-cw** [cloudwalk/stratus#961]
I'm under the impression that this snippet:

https://github.com/cloudwalk/stratus/blob/6f0a8a3dfac432529e2319264eb666ca9047a571/.github/workflows/e2e-contracts.yml#L68-L75

could be replaced with this:

```yaml
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
```

**If you guys plan to use asdf version manager...**

I noticed that (as of time of this writing) this repo does not have `.tool-versions` file (the file used by asdf-vm). If you guys plan to use it, the "Install Node.js" step could be like this:

```yaml
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
```

cc @mayconamaroCW
